settings:
  general:
    verbose: false
  commands:
    weatherwand:
      description: "The command /weatherwand presents the default help menu screen!"
      aliases: ["ww", "weatherw", "wwand"]
    help:
      description: "The command /weatherwand help <command> gives a more detailed explanation of what the command does!"
      aliases: ["h"]
    openGui:
      description: "The command /weatherwand openGui opens the WeatherWand GUI!"
      aliases: ["opengui", "og"]